#!/bin/sh

if [ $# -eq 0 ]; then
    echo "Usage: $0 SPS-pDAQ-run-XXXXXX-*.tar.gz [SPS-pDAQ-run-YYYYYY-*.tar.gz ...]"
    exit 1
fi

while [ $# -gt 0 ]; do
    for file in $1; do
        if [ ! -f "$file" ]; then
            echo "$0: Cannot find input file $1 ($file)" 1>&2
        else
            base=`basename $file .tar.gz`

            tar xvzf $file &&
            rm $file $base.meta.xml &&
            tar xvf $base.dat.tar &&
            rm $base.dat.tar
        fi
    done
    shift
done
