#!/bin/sh

if [ $# -eq 0 ]; then
   file=$HOME/Downloads/download.gz
else
   file=`ls $1`
fi

if [ ! -f "$file" ]; then
    echo "$0: Cannot find input file $1 ($file)" 1>&2
    exit 1
fi

base=`basename $file .tar.gz`

tar xvzf $file &&
rm $file $base.meta.xml &&
tar xvf $base.dat.tar &&
rm $base.dat.tar
